# Generated by Django 2.2.6 on 2019-11-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('country', models.IntegerField(choices=[(1, 'France'), (2, 'Belgium'), (3, 'Germany')])),
                ('city', models.CharField(max_length=32)),
                ('t_and_c', models.BooleanField(default=False, verbose_name='Accept terms and conditions')),
                ('language', models.ManyToManyField(to='djapp.Language')),
            ],
        ),
    ]
